FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_AURORA_CLOUD_API_BASE
ARG VITE_APP_NAME
ARG VITE_APP_VERSION
ARG VITE_MT5_SALES_ENABLED=false
ARG VITE_XAU_SALES_ENABLED=false

ENV VITE_AURORA_CLOUD_API_BASE=$VITE_AURORA_CLOUD_API_BASE
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_MT5_SALES_ENABLED=$VITE_MT5_SALES_ENABLED
ENV VITE_XAU_SALES_ENABLED=$VITE_XAU_SALES_ENABLED

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY deploy/website/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
