events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    upstream aurora_website {
        server aurora-website:8080;
    }

    upstream aurora_commerce {
        server aurora-commerce-api:8080;
    }

    server {
        listen 80;
        server_name aurorahy.com www.aurorahy.com;

        location / {
            proxy_pass http://aurora_website;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /commerce/ {
            proxy_pass http://aurora_commerce/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
